### ISSUE TITLE
add facets to intent casting component

### ISSUE THREAD

**Issue by sarah-arrrgh** [root-systems/cobuy#190]
related to 
#146
and
#39

**Comment by sarah-arrrgh** [comment]
**TODO:**

- [x] mock data for facets
- [x] add productFacet to singleViewProduct component for each facet
- [x] ensure facet data is submitted properly
